/**
 * Generated by nik on 28/12/2019
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_BOOK_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_BOOK_H

#pragma once


#include "db/orm/entity.h"

struct author_book {
	uint id_author_book;
	struct book* book;
	struct author* author;
};

typedef struct author_book AUTHOR_BOOK;

uint author_book_insert(AUTHOR_BOOK* author_bookT);

SQL_RESULT* author_book_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

AUTHOR_BOOK* author_book_find_by_id(uint id);

int author_book_update(AUTHOR_BOOK* author_bookT);

int author_book_execute(char const* query, MYSQL_BIND* params, uint param_count);

int author_book_delete(AUTHOR_BOOK* author_bookT);

SQL_RESULT* author_book_find_all();

#endif
