/**
 * Generated by nik on 28/12/2019
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_H

#pragma once


#include "db/orm/entity.h"

struct author {
	uint id_author;
	struct person* person;
	char description[4096];
};

typedef struct author AUTHOR;

uint author_insert(AUTHOR* authorT);

SQL_RESULT* author_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

AUTHOR* author_find_by_id(uint id);

int author_update(AUTHOR* authorT);

int author_execute(char const* query, MYSQL_BIND* params, uint param_count);

int author_delete(AUTHOR* authorT);

SQL_RESULT* author_find_all();

#endif
