/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_AUTHOR_H
#define __nik_DB_STRUCT_AUTHOR_H

struct author {
	uint id_author;
	struct person* person;
	char description[4096];
};

typedef struct author AUTHOR;

uint author_insert(AUTHOR* authorT);

SQL_RESULT* author_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

AUTHOR* author_find_by_id(uint id);

int author_update(AUTHOR* authorT);

int author_execute(char const* query, MYSQL_BIND* params, uint param_count);

int author_delete(AUTHOR* authorT);

#endif
