/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_BOOK_SPECIMEN_H
#define __nik_DB_STRUCT_BOOK_SPECIMEN_H

struct book_specimen {
	uint id_book_specimen;
	struct library* library;
	struct book* book;
	char book_serial[16];
};

typedef struct book_specimen BOOK_SPECIMEN;

uint book_specimen_insert(BOOK_SPECIMEN* book_specimenT);

SQL_RESULT* book_specimen_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

BOOK_SPECIMEN* book_specimen_find_by_id(uint id);

int book_specimen_update(BOOK_SPECIMEN* book_specimenT);

int book_specimen_execute(char const* query, MYSQL_BIND* params, uint param_count);

int book_specimen_delete(BOOK_SPECIMEN* book_specimenT);

#endif
