/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_BOOK_H
#define __nik_DB_STRUCT_BOOK_H

struct book {
	uint id_book;
	char isbn[32];
	char name[255];
};

typedef struct book BOOK;

uint book_insert(BOOK* bookT);

SQL_RESULT* book_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

BOOK* book_find_by_id(uint id);

int book_update(BOOK* bookT);

int book_execute(char const* query, MYSQL_BIND* params, uint param_count);

int book_delete(BOOK* bookT);

#endif
