/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_MUNICIPALITY_H
#define __nik_DB_STRUCT_MUNICIPALITY_H

struct municipality {
	uint id_municipality;
	struct region* region;
	char name[255];
};

typedef struct municipality MUNICIPALITY;

uint municipality_insert(MUNICIPALITY* municipalityT);

SQL_RESULT* municipality_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

MUNICIPALITY* municipality_find_by_id(uint id);

int municipality_update(MUNICIPALITY* municipalityT);

int municipality_execute(char const* query, MYSQL_BIND* params, uint param_count);

int municipality_delete(MUNICIPALITY* municipalityT);

#endif
