/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_PERSON_H
#define __nik_DB_STRUCT_PERSON_H

struct person {
	uint id_person;
	char first_name[255];
	char last_name[255];
	char jmbg[13];
};

typedef struct person PERSON;

uint person_insert(PERSON* personT);

SQL_RESULT* person_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

PERSON* person_find_by_id(uint id);

int person_update(PERSON* personT);

int person_execute(char const* query, MYSQL_BIND* params, uint param_count);

int person_delete(PERSON* personT);

#endif
