/**
 * Generated by nik on 26/12/2019
 */
#ifndef __nik_DB_STRUCT_READER_H
#define __nik_DB_STRUCT_READER_H

struct reader {
	uint id_reader;
	char username[255];
	char password[255];
};

typedef struct reader READER;

uint reader_insert(READER* readerT);

SQL_RESULT* reader_execute_find(char const* query, MYSQL_BIND* params, uint param_count);

READER* reader_find_by_id(uint id);

int reader_update(READER* readerT);

int reader_execute(char const* query, MYSQL_BIND* params, uint param_count);

int reader_delete(READER* readerT);

#endif
